import "./globals.css";
import { Inter, Acme, Roboto_Mono, Palanquin } from 'next/font/google';
import Navigation from "./component/Navigation/Navigation";

const acme = Acme({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-acme',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
});

const palanquin = Palanquin({
  subsets: ['latin', 'devanagari'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-palanquin',
});

export const metadata = {
  title: "Mokshit Shah Portfolio",
  description: "Generated by Mokshit Shah",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${acme.variable} ${palanquin.variable} ${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
        <Navigation/>
      </body>
    </html>
  );
}
