import "./globals.css";
import { acme, inter, robotoMono, palanquin } from './font.ts'
import Navigation from "./component/Navigation/Navigation";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${acme.variable} ${palanquin.variable} ${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
        <Navigation/>
      </body>
    </html>
  );
}
